server:
  port: 8083   

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true      

spring:
  application:
    name: pessoa
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3308/cadastro_pessoa_db?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: root123

app:
  gateway:
    endpoint: http://localhost:8080/gateway/
  contaCorrentService:
    serviceId: conta-corrente
    endpoint:
      cadastroContaCorrente: /v1/admin/conta-corrente

