version: '3.1'

services:
  db-mysql:  
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: bd_conta_corrente
    volumes:
      - microservices_guiPalma:/var/lib/mysql
volumes:
  microservices_guiPalma:
      
   